---
- name: "SUMA on AIX"
  hosts: quimby01
  gather_facts: no

  tasks:

  - name: Check oslevel of system
    shell: "oslevel -s"

  - name: Expand /usr filesystem
    shell: "chfs -a size=+5G /usr"

  - name: Check for, and install, system updates
    suma:
      oslevel: 'latest'
      location: '/usr/sys/inst.images'
      action: download
      install_updates: true
    ignore_errors: True

  - name: Expand /opt filesystem
    shell: "chfs -a size=+500M /opt"

  - name: Perform YuM check-updates
    yum:
      name: '*'
      state: latest

  - name: Check for new oslevel
    shell: "oslevel -s"

  - name: Restart with newest kernel
    shell: "sleep 5 && reboot"
    async: 1
    poll: 0
