---
- name: "SUMA on AIX"
  hosts: all
  gather_facts: yes

  tasks:

  #######################################################################
  ### AIX SUMA: Range of targets
  #######################################################################

  - name: "AIX SUMA: Range of targets"
    aix_suma:
      targets: quimby[7:12]
    ignore_errors: True

    register: targets
  - debug: var=targets.debug_targets
