---
- name: "VIOS upgrade on AIX"
  hosts: all
  gather_facts: no
  vars:
    log_file: "/tmp/ansible_viosupgrade_debug.log"

  tasks:

    - name: "AIX NIM viosupgrade from list"
      aix_nim_viosupgrade:
        description: 'Upgrade vios'
        #vios_status: "{{hc_result.status }}"
        #nim_node: "{{hc_result.nim_node }}"
        vars: "{{ vars }}"
        targets: ["vios1 vios2", "vios3 vios4", "vios5"]
        actions: {'vios1': 'altdisk', 'vios5': 'altdisk', 'all_vios': 'bosinst'} 
        ios_mksysb: {'vios1': 'ios_1844B_72M', 'vios2': 'ios_1844B_72M', 'all_vios': 'ios_1848A_72M'}
        alt_disk: {'vios1': 'hdisk1', 'vios2': 'hdisk2, hdisk4'}
        user_res: {'vios3': 'file_res', 'all_vios': 'master_net_conf'}
        force: {'p7jufv1': True, 'p7jufv2': True, 'all_vios': False}

      register: upgrade_result

    - debug: var=upgrade_result


