- name: "NIM ios update on AIX playbook"
  hosts: all
  gather_facts: no
  vars:
    log_file: "/tmp/ansible_updateios_debug.log"

  tasks:
    - name: "update ios"
      update_ios:
        targets: "(gdrh9v1)(gdrh10v1,gdrh10v2)"
        #filesets: "none"
        installp_bundle: "__smit_bundle_8323538"
        lpp_source: "VIOS_225_30-lpp_source"
        accept_licenses: "yes"
        updateios_flags: "install"
        preview: "no"
        #time_limit: "mm/dd/yyyy hh:mm"

      register: result

    - debug: var=result
