---
- name: "SUMA on AIX"
  hosts: all
  gather_facts: yes

  tasks:

  #######################################################################
  ### AIX SUMA: Star with targets
  #######################################################################

  - name: "AIX SUMA: Wildcard4 with targets"
    aix_suma:
      targets: '*'
    ignore_errors: True

    register: targets
  - debug: var=targets.debug_targets
