---
- name: "YuM Check-Update"
  hosts: all
  gather_facts: yes

  tasks:

  - name: Upgrade packages, excluding kernel related packages
    yum:
      name: '*'
      state: latest
      exclude: kernel*
    register: output
  - debug: var=output
